feat(EW-4): translation trainer page
tregulovailmira/english_words_trainer pull request #3
Opened 2022-08-08 08:13 UTC by tregulovailmira

2022-08-08 08:18 UTC, tregulovailmira commented
<img width="398" alt="image" src="https://user-images.githubusercontent.com/42368450/183372356-1c802150-7a2b-4d38-a91a-8004f187ef2b.png">

2022-08-08 11:49 UTC, kuchmenko commented on lib/features/vocabulary/presentation/pages/from_english_mode_trainer.dart
> +        builder: (context, state) {
BlocBuilder?

2022-08-08 11:49 UTC, kuchmenko commented on lib/features/vocabulary/presentation/pages/from_english_mode_trainer.dart
> +    }
```
setState(() {
         wordIndex = words.isNotEmpty ? random.nextInt(words.length) : -1;
       });

```

2022-08-08 11:49 UTC, kuchmenko commented on lib/features/vocabulary/presentation/widgets/guess_word_form.dart
> +  _generateInputsList(controllersList) {
Вот такое добро лучше выносить в отдельный компонент, чтобы избежать ререндера

Во флаттере 
Кастомый компонент для рендера чего-то > функция которая содержит логику рендера компонента

2022-08-08 11:49 UTC, kuchmenko commented on lib/main.dart
> +        create: (blocContext) => di.sl<WordsListBloc>(),
А прям очень нужно оборачивать все приложение в провайдер?

2022-08-08 12:24 UTC, tregulovailmira commented on lib/features/vocabulary/presentation/pages/from_english_mode_trainer.dart
> +        builder: (context, state) {
Ну конечно, от я Валера

2022-08-08 12:25 UTC, tregulovailmira commented on lib/features/vocabulary/presentation/pages/from_english_mode_trainer.dart
> +    }
Я Валера х2

2022-08-08 12:46 UTC, tregulovailmira commented on lib/main.dart
> +        create: (blocContext) => di.sl<WordsListBloc>(),
Мне нужно было, чтобы стейт с добавленными словами пользователя был доступен в разных узлах приложения. Если юзер залогинен, то его перекидывает на страницу со списком добавленных слов, а дальше он может переходить на другие страницы, где этот список используется (пока только тренажер с переводом слов, но еще хочу какие-то другие режимы добавить). И страницы, по которым будет происходить навигация не являются дочерними для первоначальной MyVocabularyList. А если в BlocProvider оборачивать отдельные виджеты, где это нужно, то я ж так понимаю, будет создаваться новый инстанс с пустым стейтом каждый раз и нужно будет каждый раз делать запрос в базу на получение списка слов? 
Или есть какой-то более хороший способ?

2022-08-08 13:50 UTC, tregulovailmira commented on lib/features/vocabulary/presentation/widgets/guess_word_form.dart
> +  _generateInputsList(controllersList) {
done

2022-08-15 09:52 UTC, kuchmenko requested changes

2022-08-15 09:52 UTC, kuchmenko commented on lib/core/utils/validatior.dart
> +    if (char == expectedChar) {
ternary operator?

2022-08-15 09:52 UTC, kuchmenko commented on lib/features/vocabulary/presentation/pages/from_english_mode_trainer.dart
> +        return wordIndex >= 0
```
if (wordIndex == -1)  {
 return Center....
}

return GestureDetector....

```


Это уберет ненужную вложеность

2022-08-15 09:52 UTC, kuchmenko commented on lib/features/vocabulary/presentation/widgets/guess_inputs_list.dart
> +  Widget build(BuildContext context) {
А можно описание что тут рендерится?

Я виду массивы элементов, а ключей не вижу, и немного непонятно как часто этот виджет будет ререндериться

2022-08-15 10:38 UTC, tregulovailmira commented on lib/features/vocabulary/presentation/widgets/guess_inputs_list.dart
> +  Widget build(BuildContext context) {
<img width="389" alt="image" src="https://user-images.githubusercontent.com/42368450/184619085-ce609b08-c01c-40ae-8ff3-926fd64de47f.png">

это список инпутов - каждый инпут соответствует букве в слове, если это несколько слов, то вместо пробела отображается SizedBox с переносом, чтобы слова не разрывались, и если дефис, то отображается Text('-'). 
при submit'е неправильно введенные буквы будут подсвечиваться красным
Если слово введено верно, то на submit'е выводится другое слово, либо же свайпом тоже можно заменить слово

2022-09-06 09:03 UTC, kuchmenko approved these changes

2022-09-06 09:17 UTC, merged